version: '3.1'
services:
  stats-server:
    build: ./statistic/stat_service
    image: service
    container_name: service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234