version: '3.1'
services:
  statistics-client:
    build: statistic/stat_client/
    container_name: stat_client
    ports:
      - "8080:8080"
    depends_on:
      [ stat_service]
    environment:
      - STAT_CLIENT_PORT=8080
      - STAT_SERVER_ADDRESS=http://stat_service:9090

  statistics-server:
    build: statistic/stat_service/
    container_name: stat_service
    ports:
      - "9090:9090"
    depends_on:
      [ statistics-db ]
    environment:
      STAT_SERVER_PORT: 9090
      DB_HOST: emw_statistics_db
      DB_PORT: 5432
      DB_NAME: ewmstatistics
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  statistics-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: ewmstatistics
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    hostname: emw_statistics_db