DROP TABLE IF EXISTS apps, endpoint_hits;

CREATE TABLE apps
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    CONSTRAINT pk_apps PRIMARY KEY (id)
);

CREATE TABLE endpoint_hits
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id  BIGINT REFERENCES apps(id),
    uri VARCHAR(255)                            NOT NULL,
    ip VARCHAR(31)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_endpoint_hits PRIMARY KEY (id)
);