CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL,
    name  VARCHAR NOT NULL,
    CONSTRAINT unique_user_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT unique_category_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT8 NOT NULL,
    lon FLOAT8 NOT NULL
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR   NOT NULL,
    category_id        BIGINT REFERENCES category (id),
    created_on         TIMESTAMP NOT NULL,
    description        VARCHAR,
    event_date         TIMESTAMP NOT NULL,
    initiator_id       BIGINT REFERENCES users (id),
    location_id        BIGINT REFERENCES location (id),
    paid               BOOLEAN   NOT NULL,
    participant_limit  INTEGER   NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN   NOT NULL,
    state              VARCHAR   NOT NULL,
    title              VARCHAR   NOT NULL,
    CONSTRAINT ck_event_date CHECK (event_date > now() + interval '2hour')
    );

CREATE TABLE IF NOT EXISTS participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP NOT NULL,
    event_id     BIGINT REFERENCES event (id),
    requester_id BIGINT REFERENCES users (id),
    status       VARCHAR   NOT NULL,
    CONSTRAINT unique_event_requester UNIQUE (event_id, requester_id)
    );

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title  VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT REFERENCES compilation (id),
    event_id       BIGINT REFERENCES event (id),
    CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id)
    );

CREATE TABLE IF NOT EXISTS rating_event
(
    user_id        BIGINT REFERENCES users (id),
    event_id       BIGINT REFERENCES event (id),
    rating         VARCHAR NOT NULL,
    CONSTRAINT pk_rating_event PRIMARY KEY (user_id, event_id)
    );